name: Build & Publish

on:
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    - cron: '0 0 * * 0'

env:
  IMAGE_NAME: udpxy

jobs:
  push:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Setup - QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Setup - BuildKit
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver: docker-container

      - name: Setup - Variables
        id: prep
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          SHORTREF=${GITHUB_SHA::8}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          TAGS="${IMAGE_ID}:${VERSION},${IMAGE_ID}:${SHORTREF}"
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && TAGS="$TAGS,${IMAGE_ID}:latest"
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo TAGS=$TAGS
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=image_id::${IMAGE_ID}

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build + Publish
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          labels: |
            runnumber=${{ github.run_number }}
            runid=${{ github.run_id }}
          push: true
          pull: true

